language: android
before_script: ./pre-build.sh
jdk: openjdk7
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
script: gradle build connectedCheck --info

