language: android
before_script: ./pre-build.sh && sed -i "s#com.android.tools.build:gradle:.*'#com.android.tools.build:gradle:1.5.0'#" build.gradle
jdk: openjdk7
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-24
    - extra-android-m2repository
script: gradle build connectedCheck -PbuildServer

